---
name: Publish Pages

on:
  push:

jobs:
  Pages:
    runs-on: [ubuntu-24.04]

    permissions:
      actions: read # Required to download repository artifact.
      contents: read # Required to checkout repository.
      id-token: write # Required to authenticate via OIDC.
      pages: write # Required to publish GitHub Pages.

    concurrency:
      cancel-in-progress: true
      group: pages

    environment:
      name: github-pages
      url: ${{ steps.publish.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          cache: npm
          node-version: 22

      - name: Cache Node modules
        id: cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          key: node-modules-${{ hashFiles('package-lock.json') }}
          path: node_modules

      - name: Install Node modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Setup GitHub Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0

      - name: Build GitHub Pages
        run: npm run build

      - name: Upload GitHub Pages
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: dist
          retention-days: 1

      - name: Publish GitHub Pages
        id: publish
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
        with:
          preview: true
